name: test deploy

on:
    # To have workflow starter button
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            #checkout repo
            - name: Checkout Action
              uses: actions/checkout@v3

            #Setup Node
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            #Install dependencies
            - name: Install dependencies
              run: npm install

            #Build App
            - name: Build Project
              run: npm run build

            #Deploy to github pages
            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  publish-dir: dist
